//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Two
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Record
    {
        [Display(Name = "Record ID")]
        public int RecordID { get; set; }
        [Display(Name = "User ID")]
        public string PatientID { get; set; }
        [Display(Name = "Record Date")]
        public Nullable<System.DateTime> Date { get; set; }
        [Display(Name = "Bought Medicine Name")]
        public string Bought_Medicine { get; set; }
        [Display(Name = "Reason of buying")]
        public string Buying_Reason { get; set; }
        [Display(Name = "Comment")]
        public string Comment { get; set; }
    }
}
