//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Two
{
    using System;
    using System.Collections.Generic;
    
    public partial class Record
    {
        public int RecordID { get; set; }
        public string PatientID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Bought_Medicine { get; set; }
        public string Buying_Reason { get; set; }
        public string Comment { get; set; }
    }
}
